Add boinc.subfolder.conf.sample
linuxserver/reverse-proxy-confs pull request #211
Opened 2020-09-28 00:54 UTC by davidjharder

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2020-09-28 01:50 UTC, nemchik requested changes

2020-09-28 01:50 UTC, nemchik commented on boinc.subfolder.conf.sample
> +    proxy_buffering off;
Can we move this down under the rewrite line?

2020-09-29 02:47 UTC, davidjharder commented
Moved the line, but this seems out of line with, for example, recent changes to `guacamole`

2020-10-04 14:10 UTC, aptalca approved these changes

2020-10-04 14:40 UTC, nemchik approved these changes

2020-10-04 14:43 UTC, nemchik commented
> Moved the line, but this seems out of line with, for example, recent changes to `guacamole`

The order doesn't truly matter, but all of our samples keep anything generic in order and anything custom for a specific proxy at the bottom. Thanks for fixing it.

2020-10-04 14:43 UTC, merged