fix config
linuxserver/reverse-proxy-confs pull request #236
Opened 2020-10-26 14:33 UTC by wjhrdy

This config was incomplete. 
The api path is needed for the server to be accessible.
Otherwise you run into problems like this.
https://old.reddit.com/r/homeassistant/comments/6rgf04/frontend_unable_to_connect/

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2020-10-26 14:56 UTC, aptalca commented
Hmm, sad that the linked report is from 3 years ago, yet no one notified us on any of our channels. Unfortunately we don't prowl reddit for bugs. 

Thanks so much for the PR

2020-10-26 14:58 UTC, aptalca commented on homeassistant.subdomain.conf.sample
> +        proxy_http_version 1.1;
Can you remove these 3 lines as they are already handled in the proxy.conf?
https://github.com/linuxserver/docker-swag/blob/master/root/defaults/proxy.conf
Thanks

2020-10-26 14:59 UTC, aptalca commented on homeassistant.subdomain.conf.sample
> +        proxy_http_version 1.1;
And include proxy.conf instead like above?

2020-12-03 23:51 UTC, nemchik requested changes

2020-12-03 23:51 UTC, nemchik commented on homeassistant.subdomain.conf.sample
> +        include /config/nginx/proxy.conf;
```suggestion
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
```

2020-12-10 00:49 UTC, nemchik approved these changes

2020-12-10 00:49 UTC, merged