Create amule-subdomain.conf.sample
linuxserver/reverse-proxy-confs pull request #290
Opened 2021-02-10 08:40 UTC by wswv

Initial release.

the reference docker-compose.yaml file is below:

```
version: '2'
services:
  amule:
    image: tchabaud/amule
    ports:
      - "4711:4711"7#web
      - "4662:4662"#amule used, need to expose to WAN
      - "4672:4672/udp"#amule used, need to expose to WAN
    environment:
      - PUID=1000
      - GUID=1000
    volumes:
      - ./conf:/home/amule/.aMule
      - ./amule/data:/incoming
      - ./amule/tmp:/temp
networks:
  default:
    external: 
      name: SWAG
```

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2021-02-10 14:41 UTC, nemchik requested changes
Thanks for getting this started, but we need the date comment on the first line, and you will need to read the rest of the comments in the file and follow the template instructions in order for this to be merged.

2021-02-21 17:20 UTC, Roxedus requested changes

2021-02-21 17:20 UTC, Roxedus commented on amule.subdomain.conf.sample
> +    # }
Do what it says

2021-05-22 14:01 UTC, Roxedus requested changes

2021-05-22 14:01 UTC, Roxedus commented on amule.subdomain.conf.sample
> +        resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-08-08 13:42 UTC, Roxedus commented
Closed as requested changes has not been implemented.

2021-08-08 13:42 UTC, closed without merging