Add Foundry VTT subdomain
linuxserver/reverse-proxy-confs pull request #304
Opened 2021-03-06 11:02 UTC by Sakujakira

Added capabillity for hosting [Foundry VTT](https://foundryvtt.com/).

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Aiming to resolve Issue #303 

##  Thanks, team linuxserver.io

2021-03-18 00:29 UTC, Roxedus requested changes

2021-03-18 00:29 UTC, Roxedus commented on foundryvtt.subdomain.conf.sample
> +        set $upstream_port <port>;
Please fill these

2021-04-22 14:55 UTC, Sakujakira commented on foundryvtt.subdomain.conf.sample
> +        set $upstream_port <port>;
I`ve changed these two lines and updated this merge request

2021-05-22 13:56 UTC, Roxedus requested changes

2021-05-22 13:56 UTC, Roxedus commented on foundryvtt.subdomain.conf.sample
> +        resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-05-22 13:56 UTC, Roxedus commented on foundryvtt.subdomain.conf.sample
> +        proxy_set_header X-Forwarded-Proto $scheme;
These are covered in the included proxy.conf.
https://github.com/linuxserver/docker-swag/blob/master/root/defaults/proxy.conf#L26-L28

2021-06-05 19:13 UTC, closed without merging