Create rclone.subfolder.conf.sample
linuxserver/reverse-proxy-confs pull request #307
Opened 2021-03-19 20:19 UTC by STaRDoGG

Based on the WebUI container for rClone, here: https://hub.docker.com/r/romancin/rclonebrowser

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2021-05-22 14:00 UTC, Roxedus requested changes

2021-05-22 14:00 UTC, Roxedus commented on rclone.subfolder.conf.sample
> +    resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-05-22 14:00 UTC, Roxedus commented on rclone.subfolder.conf.sample
> +     resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-05-28 14:36 UTC, Roxedus commented
Your latest push messed up all the PRs

2021-05-29 03:27 UTC, STaRDoGG commented
> Your latest push messed up all the PRs

@Roxedus How?

All I did was click on Edit paste the line and save it. Admittedly, I'm roughly only a 4/10 as far as my GH skills go, because I rarely use it.

2021-05-29 11:33 UTC, Roxedus commented
All your PRs became the petio subfolder 😅

2021-05-31 02:15 UTC, STaRDoGG commented
> All your PRs became the petio subfolder 😅

@Roxedus Ughhh. No idea how tf that even happened. Save me some time and tell me the quickest/easist way to fix it? lmao.

I might end up just saying fuggit and letting someone else pr them. Ain nobody gat time fadis. lol

2021-06-01 02:40 UTC, STaRDoGG commented
In retrospect I think I know what might've happened. I have a form recovery browser extension that may have gone kablooey and run amuck. Derp.

I'll revist all of my recent PR's and update with the previous code + the requested change in the coming week. Again, not being too good w/GH yet, I'd like to simply delete the previous mess and add the new ones, but I've also run into weird GH methods just trying that as well; like not being able to delete and having to "smush" it instead, or some weird ish like that. LOL.

2021-06-05 18:00 UTC, Roxedus approved these changes

2021-06-05 18:00 UTC, merged