Added Komga Subfolder Configuration
linuxserver/reverse-proxy-confs pull request #318
Opened 2021-04-22 15:23 UTC by Sakujakira

I have made another sample Config, this time for Komga Comic Mediaserver. 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Changes and configurations are from https://komga.org/installation/configuration.html#optional-configuration
https://komga.org/

##  Thanks, team linuxserver.io

2021-05-22 13:54 UTC, Roxedus requested changes

2021-05-22 13:54 UTC, Roxedus commented on komga.subfolder.conf.sample
> +    resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-05-22 13:54 UTC, Roxedus commented on komga.subfolder.conf.sample
> +     resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-06-06 13:29 UTC, Sakujakira commented on komga.subfolder.conf.sample
> +     resolver 127.0.0.11 valid=30s;
Done

2021-06-06 15:17 UTC, Roxedus approved these changes

2021-06-06 15:19 UTC, merged