Create petio.subfolder.conf.sample
linuxserver/reverse-proxy-confs pull request #319
Opened 2021-04-24 00:12 UTC by STaRDoGG

Subfolder reverse proxy conf for the Petio container: https://hub.docker.com/r/hotio/petio

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2021-05-22 13:54 UTC, Roxedus requested changes

2021-05-22 13:54 UTC, Roxedus commented on petio.subfolder.conf.sample
> +    resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-06-04 19:33 UTC, STaRDoGG commented
@Roxedus This one should be fine

2021-06-05 17:58 UTC, Roxedus approved these changes

2021-06-05 17:59 UTC, merged