Created chevereto proxy sample
linuxserver/reverse-proxy-confs pull request #322
Opened 2021-04-27 00:40 UTC by rastacalavera

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

made this since this image is offered by LSIO and one currently does not exist.
##  Thanks, team linuxserver.io

2021-04-27 00:44 UTC, aptalca commented on chevereto.subdomain.conf.sample
> +## Version 2020/12/09
These two lines seem to be forgotten

2021-04-27 13:03 UTC, rastacalavera reviewed
woops must have deleted that, thanks

2021-05-22 13:52 UTC, Roxedus requested changes

2021-05-22 13:52 UTC, Roxedus commented on chevereto.subdomain.conf.sample
> +        resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-06-29 17:51 UTC, drizuid commented
closing as https://github.com/linuxserver/reverse-proxy-confs/pull/350 was merged

2021-06-29 17:51 UTC, closed without merging