Create hass-configurator.subdomain.conf.sample
linuxserver/reverse-proxy-confs pull request #329
Opened 2021-05-13 00:52 UTC by kerta1n

this proxy configuration file is for the hass-configurator-docker container that is used in the hassos addon store (https://github.com/CausticLab/hass-configurator-docker)

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2021-05-22 13:48 UTC, Roxedus requested changes

2021-05-22 13:48 UTC, Roxedus commented on hass-configurator.subdomain.conf.sample
> +# this proxy configuration file is for the hass-configurator-docker container that is used
Add a date.

2021-06-02 11:20 UTC, kerta1n commented
Seems I did not enter the date as requested by format. This should be fixed now.

2021-06-04 20:04 UTC, drizuid approved these changes

2021-06-05 17:57 UTC, Roxedus requested changes

2021-06-05 17:57 UTC, Roxedus commented on hass-configurator.subdomain.conf.sample
> +        resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-06-05 20:09 UTC, Roxedus approved these changes

2021-06-05 20:09 UTC, merged