Create a mealie.subdomain.conf.sample for mealie recipe app
linuxserver/reverse-proxy-confs pull request #331
Opened 2021-05-21 12:35 UTC by zierbeek

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

2021-05-22 13:43 UTC, Roxedus requested changes

2021-05-22 13:43 UTC, Roxedus commented on mealie.subdomain.conf.sample
> +        resolver 127.0.0.11 valid=30s;
Please update this to reflect the changes brought by #330

2021-05-22 21:18 UTC, zierbeek commented on mealie.subdomain.conf.sample
> +        resolver 127.0.0.11 valid=30s;
Normally it's fixed now! Apologies

2021-05-22 21:19 UTC, aptalca approved these changes

2021-05-24 19:40 UTC, Roxedus approved these changes

2021-05-24 19:40 UTC, merged