Auto redirect for non-standard port
linuxserver/reverse-proxy-confs pull request #378
Opened 2021-09-12 00:42 UTC by wswv

Purpose to add function to auto redirect to non-standard port when server works on non-standard port condition.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2021-09-12 00:45 UTC, wswv reviewed
test passed in my server

2021-09-12 01:02 UTC, nemchik requested changes

2021-09-12 01:02 UTC, nemchik commented on calibre-web.subdomain.conf.sample
> +	proxy_redirect https://$host/ https://$host:selfdefined port number/;#here use your self-defined port number, so it could redirect to other link then still keep self defined port number.
```suggestion
        proxy_redirect https://$host/ https://$host:selfdefined port number/;#here use your self-defined port number, so it could redirect to other link then still keep self defined port number.
```
Matching indent

2021-09-12 01:06 UTC, nemchik commented
Also, can you set the upstream port variable and then use that variable in your line?

Ex:
```nginx
        set $upstream_port 8444;
...
	proxy_redirect https://$host/ https://$host:$upstream_port/;
```

2021-09-12 01:07 UTC, nemchik commented
Lastly, I think we might want this line commented by default. I'm thinking not everyone will be wanting do forward to a custom port in this way.

2022-10-04 20:25 UTC, drizuid commented
OP didn't make the adjustments requested and swag has been revamped requiring a re-work. closing this.

2022-10-04 20:25 UTC, closed without merging