Create gaps.subdomain.conf.sample
linuxserver/reverse-proxy-confs pull request #394
Opened 2021-10-20 22:08 UTC by trolley

For container: https://hub.docker.com/r/housewrecker/gaps

Also fix small typo in portainer.subdirectory.conf.sample.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2021-10-20 22:09 UTC, trolley commented
Subfolder sample was added in PR #325.

2021-11-04 14:50 UTC, drizuid commented on portainer.subfolder.conf.sample
> +    proxy_hide_header X-Frame-Options; # Possibly not needed after Portainer 1.20.0
"possibly" doesn't instill much confidence, please thoroughly test, we won't support a change that could break users.

2021-11-04 14:53 UTC, drizuid commented on portainer.subfolder.conf.sample
> +    proxy_hide_header X-Frame-Options; # Possibly not needed after Portainer 1.20.0
this correction was made sep1, 2020

2021-11-04 14:54 UTC, trolley commented on portainer.subfolder.conf.sample
> +    proxy_hide_header X-Frame-Options; # Possibly not needed after Portainer 1.20.0
I'm not sure what you're referring to. This file in the `master` branch currently has `nott` misspelled: https://github.com/linuxserver/reverse-proxy-confs/blob/master/portainer.subfolder.conf.sample

2021-11-04 14:54 UTC, drizuid requested changes
disregard, another typo was missed

2021-11-04 14:55 UTC, drizuid commented on portainer.subfolder.conf.sample
> +    proxy_hide_header X-Frame-Options; # Possibly not needed after Portainer 1.20.0
i stand corrected, i missed that one

2021-11-04 14:55 UTC, trolley commented
> please remove the portainer config as it's superfluous per [54ede40#diff-b0f0b1ac69c24158e8d491aa7f372ec5fbdf57ad0a9423e94c334dc44b27bf66](https://github.com/linuxserver/reverse-proxy-confs/commit/54ede409381b58e6b13d310fa9af623f42948072#diff-b0f0b1ac69c24158e8d491aa7f372ec5fbdf57ad0a9423e94c334dc44b27bf66)

That's a different line. In `master` the same comment appears on lines 28 and 40, and I'm just correcting the typo on line 28.

If you'd prefer a separate PR for that change I'm good to do that though.

2021-11-04 14:56 UTC, drizuid approved these changes

2021-11-04 14:56 UTC, merged

2021-11-04 14:56 UTC, trolley commented
Thanks @drizuid.