Added Duplicacy configuration files
linuxserver/reverse-proxy-confs pull request #419
Opened 2022-01-18 04:32 UTC by morpheus65535

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2022-07-01 11:16 UTC, Roxedus requested changes
The 307 and 301 redirects should be consolidated, i would also see if one could do a condition for the returns, like the plex subfolder example

2022-07-01 12:59 UTC, morpheus65535 commented
> The 307 and 301 redirects should be consolidated, i would also see if one could do a condition for the returns, like the plex subfolder example

I don't see how it can be done since for Plex all the file reside in a `web` subdirectory where duplicacy store it's files at root. Doind the same as plex would mean that every requests for any location would result in a redirect to duplicacy.

Maybe someone else will come with a hint on how to fix this but I don't see any cleaner than what I did.

2023-02-14 14:13 UTC, nemchik requested changes
The proxy templates have been updated with new descriptive comments and auth lines. Please update your PR accordingly.

Ref:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subfolder.conf.sample

2023-04-13 18:12 UTC, nemchik commented on duplicacy.subfolder.conf.sample
> +}
All these locations are not beneath the subfolder (ex: `location /duplicacy/update_listing_session {`)
Does this app actually work with subfolder?

2023-04-16 11:50 UTC, morpheus65535 commented on duplicacy.subfolder.conf.sample
> +}
Yes but it's not perfect. It require to add each and every path in the proxy config and conflict may happens with other software. Not sure if it's robust enough to be included anymore.

2023-04-16 14:51 UTC, nemchik commented on duplicacy.subfolder.conf.sample
> +}
Let's just keep the subdomain file for now. If you don't mind, delete the subfolder file and i'll review/accept the subdomain conf.

2023-04-19 10:13 UTC, morpheus65535 commented on duplicacy.subfolder.conf.sample
> +}
Done!

2023-04-23 12:32 UTC, nemchik approved these changes

2023-04-23 12:32 UTC, merged