Add CloudBeaver sample config
linuxserver/reverse-proxy-confs pull request #427
Opened 2022-02-20 10:27 UTC by ofersadan85

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2022-02-20 13:11 UTC, Roxedus commented
Please fix the line endings

2022-02-20 15:39 UTC, ofersadan85 commented
@Roxedus done, sorry about that

2022-02-20 23:09 UTC, Roxedus requested changes

2022-02-20 23:09 UTC, Roxedus commented on cloudbeaver.subdomain.conf.sample
> +
Please keep this line consistent with the template

2022-02-21 09:22 UTC, ofersadan85 commented on cloudbeaver.subdomain.conf.sample
> +
done, hopefully

2022-02-23 16:57 UTC, merged