Added sample config for linuxserver/grav
linuxserver/reverse-proxy-confs pull request #430
Opened 2022-03-09 08:57 UTC by ofersadan85

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2022-06-30 19:22 UTC, Roxedus commented on grav.subfolder.conf.sample
> +# In order to use this location block you need to edit the default file one folder up and comment out the / location
Pretty sure the php location also interferes.

2022-06-30 19:23 UTC, Roxedus requested changes
See note

2022-07-04 06:41 UTC, ofersadan85 commented on grav.subfolder.conf.sample
> +# In order to use this location block you need to edit the default file one folder up and comment out the / location
When I tested this (been a while) I remember not touching the php location and it worked fine. Would you be able to test to verify if this is needed @Roxedus ?

2022-08-16 14:52 UTC, ofersadan85 commented
@Roxedus see my question on your review

2022-08-17 13:02 UTC, Roxedus commented
I have no environment handy to test this, i just know it was a issue with the organizr, and possibly the heimdall contaieners, which both are PHP based.

2023-01-26 08:40 UTC, closed without merging