Add searx subdomain
linuxserver/reverse-proxy-confs pull request #448
Opened 2022-05-26 18:10 UTC by HelamanWarrior

Added searx subdomain, works just fine for me. Let me know if anything needs to be changed. 
Thanks!

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2022-06-30 18:49 UTC, Roxedus requested changes

2022-06-30 18:49 UTC, Roxedus commented on searx.subdomain.conf.sample
> +        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
duplicates, also exists in the [proxy.conf](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/proxy.conf)

2022-07-02 15:12 UTC, HelamanWarrior commented on searx.subdomain.conf.sample
> +        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
Alrighty thanks, just removed the duplicates.

2022-11-30 11:32 UTC, KasperSkytte commented
Don't we also need some `uwsgi_param`'s in `location / {}`? see https://www.maketecheasier.com/create-search-engine-searxng/#configure-searxng

```
uwsgi_pass unix:///usr/local/searxng/run/socket;
include uwsgi_params;
uwsgi_param    HTTP_HOST             $host;
uwsgi_param    HTTP_CONNECTION       $http_connection;
uwsgi_param    HTTP_X_SCHEME         $scheme;
uwsgi_param    HTTP_X_SCRIPT_NAME    /searxng;
uwsgi_param    HTTP_X_REAL_IP        $remote_addr;
uwsgi_param    HTTP_X_FORWARDED_FOR  $proxy_add_x_forwarded_for;
```

2023-03-19 02:38 UTC, closed without merging