fireflyiii family subdomain sample configs
linuxserver/reverse-proxy-confs pull request #455
Opened 2022-06-26 16:40 UTC by nomandera

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2022-06-30 18:40 UTC, Roxedus commented on fireflyiii-importer.subdomain.conf.sample
> +# fireflyiii-importer will require `TRUSTED_PROXIES=**` variable or similar
Does it work with setting `TRUSTED_PROXIES` to `swag`. or should we recommend the whole default docker bridge block?

2022-07-01 10:11 UTC, nomandera commented on fireflyiii-importer.subdomain.conf.sample
> +# fireflyiii-importer will require `TRUSTED_PROXIES=**` variable or similar
According to [documentation](https://docs.firefly-iii.org/firefly-iii/installation/docker/)

`TRUSTED_PROXIES which must be set to either the reverse proxy machine or simply **`

I have made this change and it seems to work with fireflyiii but not fireflyiii-importer.

I will update the PR once I make them both work.

Nice catch.

2022-07-02 13:12 UTC, nomandera commented on fireflyiii-importer.subdomain.conf.sample
> +# fireflyiii-importer will require `TRUSTED_PROXIES=**` variable or similar
I spoke too soon. Something expired with the `TRUSTED_PROXIES` set to anything other than `**` you can no longer authenticate.

Happy to try anything else we can think of but at this point it looks the only reliable option is the default.

Worth noting the sample .env file makes no reference to any other options

https://github.com/firefly-iii/firefly-iii/blob/main/.env.example#L32-L34

My take on this is that for now at least we just add a line to the PR samples giving context.

2023-02-17 13:35 UTC, nemchik requested changes
The proxy templates have been updated with new descriptive comments and auth lines. Please update your PR accordingly.

Ref:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subfolder.conf.sample

2023-02-18 09:06 UTC, nomandera commented
I cannot make this work reliably and am currently porting away from Firefly-iii because of this and other edge case complications.

Closing PR as I will likely never be able to fix it.

2023-02-18 09:06 UTC, closed without merging