Proxy conf for Leantime
linuxserver/reverse-proxy-confs pull request #467
Opened 2022-08-05 23:39 UTC by mentallyinspired

Proxy configuration for the project management tool Leantime.
https://leantime.io

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2022-11-27 22:00 UTC, Roxedus requested changes

2022-11-27 22:00 UTC, Roxedus commented on leantime.subdomain.conf.sample
> +## Version 2022/08/06
This should also mention the need for a CNAME

2023-02-17 13:36 UTC, nemchik requested changes
The proxy templates have been updated with new descriptive comments and auth lines. Please update your PR accordingly.

Ref:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subfolder.conf.sample

2023-02-19 08:51 UTC, mentallyinspired reviewed
DNS cname info and container name info text

2023-02-19 14:39 UTC, nemchik requested changes
Might seem real picky, but having all the comments consistent makes it easier for end users to use and easier for us to maintain (especially when we have to do mass find/replace).

2023-02-19 14:39 UTC, nemchik commented on leantime.subdomain.conf.sample
> +    #include /config/nginx/authelia-server.conf;
```suggestion
    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    #include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;
```

2023-02-19 14:39 UTC, nemchik commented on leantime.subdomain.conf.sample
> +        #include /config/nginx/authelia-location.conf;
```suggestion
        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        #include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;
```

2023-02-19 16:04 UTC, nemchik commented on leantime.subdomain.conf.sample
> +        #include /config/nginx/authelia-location.conf;
Need this one too.

2023-02-19 20:18 UTC, nemchik approved these changes
lgtm. thanks!

2023-02-19 20:19 UTC, merged