Create snipe-it proxy conf
linuxserver/reverse-proxy-confs pull request #468
Opened 2022-08-08 07:32 UTC by junkman690

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2022-08-08 07:54 UTC, junkman690 commented
This should also close issue #262

2022-11-27 22:01 UTC, Roxedus commented on snipe-it.subdomain.conf.sample
> +        set $upstream_proto https;
Is there any reason it talks to the container over https?

2023-01-06 06:48 UTC, junkman690 commented on snipe-it.subdomain.conf.sample
> +        set $upstream_proto https;
@Roxedus I honestly can't recall why I set it to https. http should also work fine.

2023-02-17 13:37 UTC, nemchik requested changes
The proxy templates have been updated with new descriptive comments and auth lines. Please update your PR accordingly.

Ref:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subfolder.conf.sample

2023-05-21 02:28 UTC, closed without merging