Add `esphome.subdomain.conf`
linuxserver/reverse-proxy-confs pull request #534
Opened 2023-02-23 18:18 UTC by golles

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description
Subdomain configuration for [ESPHome](https://esphome.io)

## Benefits of this PR and context

This is an addition to your amazing collection of configurations. I wanted to share this one

## How Has This Been Tested?
I've been using this config since Oct 7, 2020.

## Source / References

https://esphome.io

2023-03-29 17:16 UTC, golles commented
Feel free to decline this PR if you think it has no added value.

2023-04-13 18:03 UTC, nemchik requested changes
Auth lines need to be commented by default. Otherwise it looks good to me.

2023-04-13 18:03 UTC, nemchik commented on esphome.subdomain.conf.sample
> +    include /config/nginx/authelia-server.conf;
```suggestion
    #include /config/nginx/authelia-server.conf;
```

2023-04-13 19:32 UTC, golles commented on esphome.subdomain.conf.sample
> +    include /config/nginx/authelia-server.conf;
```suggestion
    #include /config/nginx/authelia-server.conf;
```

2023-04-15 11:08 UTC, golles commented
I've created #554 to replace this PR, sorry for the trouble

2023-04-15 11:08 UTC, closed without merging