Add `dsmrreader.subdomain.conf`
linuxserver/reverse-proxy-confs pull request #535
Opened 2023-02-23 18:19 UTC by golles

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description
Subdomain configuration for [DSMR-reader](https://github.com/dsmrreader/dsmr-reader)

## Benefits of this PR and context

This is an addition to your amazing collection of configurations. I wanted to share this one

## How Has This Been Tested?
I've been using this config since Dec 12, 2020.

## Source / References

https://github.com/dsmrreader/dsmr-reader

2023-03-29 17:16 UTC, golles commented
Feel free to decline this PR if you think it has no added value.

2023-04-13 18:04 UTC, nemchik requested changes
Auth lines need to be commented by default. Otherwise it looks good to me.

2023-04-13 18:04 UTC, nemchik commented on dsmrreader.subdomain.conf.sample
> +    include /config/nginx/authelia-server.conf;
```suggestion
    #include /config/nginx/authelia-server.conf;
```

2023-04-13 18:04 UTC, nemchik commented on dsmrreader.subdomain.conf.sample
> +        include /config/nginx/authelia-location.conf;
```suggestion
        #include /config/nginx/authelia-location.conf;
```

2023-04-13 20:13 UTC, golles commented
@nemchik Thank you for the feedback, I missed restoring these lines from how I use them.
I think I screwed up both PR's. I deleted the fork of this repo (`golles closed this by deleting the head repository on Feb 23`), I was able to reopen the PR's by forking it again, however, I don't have the tracking branches any longer.
Usually, there is a commit suggestion next to a code suggestion comment.

I think I have to recreate new PR's for this, I will do this soon

2023-04-15 11:05 UTC, golles commented
That was a nice idea, but that didn't work, as there is no place where I can cherry-pick that commit from. I've created #553 te replace this PR, sorry for the trouble

2023-04-15 11:05 UTC, closed without merging