add kasm subdomain sample
linuxserver/reverse-proxy-confs pull request #560
Opened 2023-04-18 23:18 UTC by thelamer

Adds a subdomain conf for both the main Kasm interface and the wizard with notes about post install configuration.

2023-04-18 23:27 UTC, Roxedus commented on kasm.subdomain.conf.sample
> +        proxy_http_version      1.1;
Any reason you are shipping these, rather than including, and inheriting from proxy conf?

2023-04-18 23:35 UTC, thelamer commented on kasm.subdomain.conf.sample
> +        proxy_http_version      1.1;
I thought it was safest to follow the Kasm example to the T:  https://www.kasmweb.com/docs/latest/how_to/reverse_proxy.html#example-nginx-config

But you do make a valid point about many of them being identical, was concerned about additional vars messing with it, I will test on the VDI server and see if it has any effect.

2023-04-18 23:46 UTC, thelamer commented on kasm.subdomain.conf.sample
> +        proxy_http_version      1.1;
I remember why now it was the timeout values contradicting with the base, but I think those are very excessive and 240 is fine. I just tested on the VDI server in germany and it still worked great, it wont get much higher latency for anyone else.

2023-04-19 00:24 UTC, nemchik commented on kasm.subdomain.conf.sample
> +        proxy_http_version      1.1;
Linking for quick reference https://github.com/linuxserver/docker-swag/blob/master/root/defaults/nginx/proxy.conf.sample

The default from nginx for `proxy_connect_timeout` is `60`, and it looks like our value of `240` dates all the way back to the original addition of the proxy file in the former le repo https://github.com/linuxserver/docker-letsencrypt/commit/7a5926c8322b37330bd15ef59794c1d13b40863a

I'm not opposed to revisiting the values we ship in the proxy conf. I know most of the more recent changes and additions are as close to stock or nginx recommendations as possible, sprinkled in are things required for authelia/authentik.

2023-04-19 00:27 UTC, nemchik commented
Would there be any benefit to shipping this as two conf files (one for each server block)? Do these two things ever run as two separate containers?

2023-04-19 00:31 UTC, thelamer commented on kasm.subdomain.conf.sample
> +        proxy_http_version      1.1;
I think the 1800 in the Kasm example was likely just a "max it out" style decision to deal with problem deployments, the 240 works fine for me and worked in my testing.

2023-04-19 00:33 UTC, thelamer commented
> Would there be any benefit to shipping this as two conf files (one for each server block)? Do these two things ever run as two separate containers?

Naw it's always the same container, this container is weird that it has a web interface to properly deploy the other web interface. It is also used for upgrades. It was a way to deploy the Kasm app in an isolated DinD container instead of requiring host level installs that are not gonna be compatible with most home server solutions.

2023-04-19 01:09 UTC, nemchik requested changes

2023-04-19 01:17 UTC, nemchik approved these changes

2023-04-19 01:22 UTC, merged