added pterodactyl config
linuxserver/reverse-proxy-confs pull request #571
Opened 2023-05-08 21:30 UTC by GetLifty

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description
Adds two new subdomain config files! One is for the pterodactyl game server panel, and the other is for pterodactyl nodes.

## Benefits of this PR and context
Pterodactyl panel reverse proxy is not very well documented outside of their own implementation. When trying to set it up myself I found only one guide designed for nginx proxy manager and had to adapt from that.

## How Has This Been Tested?
Tested on my personal setup. Works perfectly including API access, SFTP and other included features. Have also tested on a friends server to similar success.

## Source / References
N/A

2023-05-19 23:16 UTC, nemchik requested changes

2023-05-19 23:16 UTC, nemchik commented on pterodactylnode.subdomain.conf.sample
> +    }
```suggestion
```
This section should go below the main location (for consistency with other confs) and could be a bit simpler. The proxy headers aren't needed (they are already included in the proxy.conf) and the regex could be simpler (covering all of the `/api` endpoint).

P.S. The whitespace (empty lines) might need cleaning up if you accept this suggestion as a commit.

2023-05-19 23:16 UTC, nemchik commented on pterodactylnode.subdomain.conf.sample
> +    }
```suggestion
    }
    
    location ~ (/pterodactylnode)?/api {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app pterodactylnode;
        set $upstream_port 443;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port/api/servers/$serverid/ws;

    }
```

2023-05-19 23:16 UTC, nemchik commented on pterodactylpanel.subdomain.conf.sample
> +## Version 2023/05/08
Can you rename this to `pterodactyl.subdomain.conf.sample`

2023-05-19 23:16 UTC, nemchik commented on pterodactylnode.subdomain.conf.sample
> +        set $upstream_proto http;
This is more of a question (just to confirm) is this meant to work on `443` using `http`? Or is it meant to be `https`?

2023-05-19 23:44 UTC, GetLifty commented on pterodactylnode.subdomain.conf.sample
> +        set $upstream_proto http;
It is meant to be http. The daemon port for the node is user selectable, but when I was researching setting my server up, it seemed the general consensus was to use 8443 or 443 (despite the fact it isnt https).

2023-05-19 23:51 UTC, GetLifty commented on pterodactylpanel.subdomain.conf.sample
> +## Version 2023/05/08
Done

2023-05-20 00:05 UTC, nemchik commented
https://github.com/linuxserver/reverse-proxy-confs/pull/571/commits/8355cdc795ef6cf74b9ba5f7d67e65928e001a47 this isn't what I meant about whitespace. Please keep 4 space indentation (not tabs). What I meant was my suggestion may have left extra empty lines as I did not account for the empty lines when highlighting. If there's no double empty lines then it's fine.

2023-05-20 00:09 UTC, GetLifty commented
> [8355cdc](https://github.com/linuxserver/reverse-proxy-confs/commit/8355cdc795ef6cf74b9ba5f7d67e65928e001a47) this isn't what I meant about whitespace. Please keep 4 space indentation (not tabs). What I meant was my suggestion may have left extra empty lines as I did not account for the empty lines when highlighting. If there's no double empty lines then it's fine.

Sorry, if you cant tell I am pretty new to github (and generally programming). My tired brain assumed that the indentation was causing the check failure and manually tried to fix it :(.

2023-05-20 00:31 UTC, GetLifty commented
Ok I reverted the commit (after spending embarrasingly long figuring out how). Still not 100% on the check failure but if its something I am missing feel free to let me know. Ive not got any more time to work today so I will likely fix this tommorow.

2023-05-20 00:33 UTC, nemchik requested changes
This should fix the failing action check.

2023-05-20 00:33 UTC, nemchik commented on pterodactylnode.subdomain.conf.sample
> +        proxy_pass $upstream_proto://$upstream_app:$upstream_port/api/servers/$serverid/ws;
```suggestion
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
```

2023-05-20 02:34 UTC, nemchik approved these changes

2023-05-20 02:34 UTC, merged