Update prowlarr.subfolder.conf.sample to create /download block
linuxserver/reverse-proxy-confs pull request #609
Opened 2023-09-13 12:24 UTC by PrivatePasta

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description
Downloads through Radarr seems to make requests to Prowlarr at /download instead of /api. In the old config, if the Authelia config is enabled, these /download requests would be blocked by Authelia

## Benefits of this PR and context
Mentioned above

## How Has This Been Tested?
Tested on latest Radarr stable (4.7.5.7809) and nightly (5.0.2.8062)

## Source / References

2023-09-15 17:04 UTC, nemchik commented
This looks fine to me, but could you also do the subfolder proxy?

2023-09-16 21:20 UTC, PrivatePasta commented
Sure, done @nemchik . Please confirm for subdomain as well, I'm not sure if the format is correct

2023-10-09 17:43 UTC, nemchik requested changes

2023-10-17 13:44 UTC, nemchik approved these changes

2023-10-17 13:44 UTC, merged