Created new configs for linkace, storm and YourSpotify
linuxserver/reverse-proxy-confs pull request #612
Opened 2023-09-29 13:33 UTC by Jurrer

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description
I am sharing my configs that I found useful.

## Benefits of this PR and context

It adds new functionality. I hope it will save people some time.

## How Has This Been Tested?

Successfully tested on own lsio nginx instance. Did not test authentication options.

## Source / References

[YourSpotify](https://github.com/Yooooomi/your_spotify)
[LinkAce](https://github.com/Kovah/LinkAce)
[Storm](https://github.com/relvacode/storm)

2023-10-09 14:37 UTC, drizuid commented on linkace.subdomain.conf.sample
> +    proxy_set_header X-Forwarded-Proto $scheme;
remove

2023-10-09 14:38 UTC, drizuid commented on linkace.subdomain.conf.sample
> +    proxy_set_header Host $host;
remove, duplicate from proxy.conf

2023-10-09 14:38 UTC, drizuid commented on linkace.subdomain.conf.sample
> +    proxy_set_header X-Forwarded-For $remote_addr;
confirm this is needed, remove it and test, overrides `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;` which is probably what is needed

2023-10-09 14:40 UTC, drizuid commented on linkace.subdomain.conf.sample
> +    add_header X-Content-Type-Options "nosniff";
we do not enforce security policies on users in this manner, they can uncomment these things in ssl.conf

2023-10-15 18:38 UTC, Jurrer commented on linkace.subdomain.conf.sample
> +    proxy_set_header X-Forwarded-For $remote_addr;
not needed, removed it

2023-10-17 14:04 UTC, nemchik requested changes

2023-10-17 14:04 UTC, nemchik commented on linkace.subdomain.conf.sample
> +
I would prefer not including these here for the sake of keeping the confs uniform. It is reasonable to add headers to individual proxies, but it's more likely that this header would be added to the `ssl.conf`.

2023-10-17 14:04 UTC, nemchik commented on storm.subdomain.conf.sample
> +
Same comment from linkace regarding this header.

2023-10-17 14:04 UTC, nemchik commented on your-spotify.subdomain.conf.sample
> +
Same comment from linkace regarding this header.

2023-10-17 14:04 UTC, nemchik commented on your-spotify.subdomain.conf.sample
> +server {
This should be a separate file, and comments at the top of both indicating if they are both required that you should enable them both.

2023-10-17 14:04 UTC, nemchik commented on your-spotify.subdomain.conf.sample
> +
Same comment from linkace regarding this header.

2023-10-17 14:31 UTC, Jurrer commented on your-spotify.subdomain.conf.sample
> +server {
done

2023-10-17 18:21 UTC, nemchik approved these changes
lgtm, thanks!

2023-10-17 18:22 UTC, merged