Flaresolverr
linuxserver/reverse-proxy-confs pull request #635
Opened 2023-12-15 22:12 UTC by Findarato

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description
I am adding support for the flaresolvrr container

## Benefits of this PR and context

## How Has This Been Tested?
I am running this config on my network currently and it works

## Source / References

2023-12-22 15:33 UTC, drizuid requested changes

2023-12-22 15:33 UTC, drizuid commented on flaresolverr.subfolder.conf.sample
> +# make sure that sonarr is set to work with the base url /sonarr/
this seems wrong...

2023-12-22 15:34 UTC, drizuid commented
> I am running this config on my network currently and it works

you tested both subdomain and subfolder?

2024-01-03 22:58 UTC, STaRDoGG commented
Works for me (subdomain)

2024-01-19 14:18 UTC, Findarato commented on flaresolverr.subfolder.conf.sample
> +# make sure that sonarr is set to work with the base url /sonarr/
Woops I will fix, copy pasta caught me

2024-01-19 19:03 UTC, drizuid commented
once someone can test/confirm subfolder, i will merge. unfortunately, OP didn't answer the question and stardogg only tested subdomain.

2024-04-24 16:24 UTC, drizuid approved these changes

2024-05-11 15:00 UTC, merged