grpc section
linuxserver/reverse-proxy-confs pull request #644
Opened 2024-01-17 20:07 UTC by drizuid

add grpc support for the app

2024-01-17 20:10 UTC, drizuid commented
thanks to thedinz

2024-02-26 09:58 UTC, Roxedus requested changes

2024-02-26 09:58 UTC, Roxedus commented on pydio-cells.subdomain.conf.sample
> +            grpc_pass grpcs://pydio-cells:33060;
Should be the $upstream_app:$upstream_port pattern.

2024-02-26 12:35 UTC, drizuid commented
putting this on hold as I don't use pydio-cells and the [documentation ](https://pydio.com/en/docs/kb/deployment/running-cells-behind-nginx-reverse-proxy)implies that the port used is the normal 8080 port. need to get confirmation/testing from someone that uses this.
![image](https://github.com/linuxserver/reverse-proxy-confs/assets/40674481/367ea65b-5ea0-4be7-831c-a7096066db45)

2024-03-14 14:41 UTC, aptalca commented on pydio-cells.subdomain.conf.sample
> +            grpc_pass grpcs://pydio-cells:33060;
done

2024-03-14 14:43 UTC, aptalca commented
upstream now defaults to 8080 for grpc, var is removed from our pydio-cells image in https://github.com/linuxserver/docker-pydio-cells/pull/17

2024-03-14 14:43 UTC, aptalca approved these changes

2024-03-14 21:08 UTC, Roxedus approved these changes

2024-03-14 21:29 UTC, merged