Create kimai.subdomain.conf.sample
linuxserver/reverse-proxy-confs pull request #659
Opened 2024-03-22 20:39 UTC by drizuid

did not test API functionality as I'm not using it

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ ] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description

## Benefits of this PR and context

## How Has This Been Tested?

## Source / References

2024-03-23 16:15 UTC, nemchik requested changes

2024-03-23 16:15 UTC, nemchik commented on kimai.subdomain.conf.sample
> +
we don't usually put the auth lines here
https://github.com/linuxserver/reverse-proxy-confs/blob/6b2e31a42bb6eceb58bc663251861b4a691c7b19/_template.subdomain.conf.sample#L51-L62
not that they can't be, but if we're going to include them here it would be better to make a separate PR and include them in all api blocks for all confs.

2024-05-11 23:20 UTC, drizuid commented on kimai.subdomain.conf.sample
> +
my bad on the delay, forgot i submitted this :D

2024-05-12 21:15 UTC, nemchik approved these changes

2024-05-18 13:04 UTC, merged