Add configurations for Sonarr to RSS
linuxserver/reverse-proxy-confs pull request #666
Opened 2024-03-31 06:19 UTC by gbendy

Add proxy configurations for Sonarr to RSS

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ X ] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description

Sonarr to RSS is a new Sonarr helper app.  

https://github.com/gbendy/sonarrToRSS/
https://registry.hub.docker.com/r/gbendy/sonarrtorss/

This PR adds both subdomain and subfolder reverse proxy support to Swag. The application supports both types of reverse proxy natively.

## Benefits of this PR and context

Users can configure swag without having to manually install configurations files from the app repository

## How Has This Been Tested?

Have been running the subdomain configuration myself for over a week with no problems.

Have run subfolder proxy for long enough to test that all endpoints work.

Have run both with authentication enabled and ensured that the 'api' endpoints are exempt from authentication and the user endpoints are not.

## Source / References

N/A

2024-04-24 16:27 UTC, drizuid approved these changes

2024-05-11 14:39 UTC, Roxedus requested changes

2024-05-11 14:39 UTC, Roxedus commented on sonarrtorss.subdomain.conf.sample
> +    }
Whats the point of these locations? they should be all covered by /

2024-05-11 14:39 UTC, Roxedus commented on sonarrtorss.subfolder.conf.sample
> +    rewrite /sonarrtorss(.*) $1 break;
Samme applies to these

2024-05-11 22:58 UTC, gbendy commented on sonarrtorss.subfolder.conf.sample
> +    rewrite /sonarrtorss(.*) $1 break;
Because these endpoints are ones that you would typically not want the authentication configured in the `/` to be applied to. Feed endpoints are usually unauthenticated and the `/sonarr` needs to use the authentication configured within the application

2024-05-21 11:53 UTC, Roxedus commented on sonarrtorss.subfolder.conf.sample
> +    rewrite /sonarrtorss(.*) $1 break;
a solution like this is more fitting then https://github.com/linuxserver/reverse-proxy-confs/blob/0947948124e5a9f5d085b13a79a38c212694546f/homeassistant.subdomain.conf.sample#L56

2024-06-21 07:25 UTC, Roxedus requested changes

2024-06-21 07:25 UTC, Roxedus commented on sonarrtorss.subfolder.conf.sample
> +location ~ ^/(api/|sonarr$|rss$|atom$|json$) {
This need the subfolder prefixed, as this will break other apps using ie api in their path.
https://github.com/linuxserver/reverse-proxy-confs/blob/master/sonarr.subfolder.conf.sample#L28

2024-06-21 09:08 UTC, gbendy commented on sonarrtorss.subfolder.conf.sample
> +location ~ ^/(api/|sonarr$|rss$|atom$|json$) {
Whoops, so it did. And it needed the rewrite.

2024-06-21 10:42 UTC, Roxedus approved these changes

2024-06-21 10:42 UTC, merged