added linkwarden configs
linuxserver/reverse-proxy-confs pull request #690
Opened 2024-08-04 21:49 UTC by jlssmt

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description
added linkwarden configs

## Benefits of this PR and context
added linkwarden configs

## Source / References
sample as base

2024-09-07 13:40 UTC, jlssmt commented
no interest here?
linkwarden has 7.6k github stars

2024-09-07 15:15 UTC, Roxedus requested changes
This has a api that might be interesting to consume. add a block excluding the api from eternal auth.

2024-09-07 15:54 UTC, jlssmt commented
> This has a api that might be interesting to consume. add a block excluding the api from eternal auth.

like this?

2024-09-12 07:32 UTC, Roxedus approved these changes

2024-09-12 07:32 UTC, Roxedus requested changes

2024-09-12 14:00 UTC, jlssmt commented on linkwarden.subfolder.conf.sample
> +    set $upstream_port 80;
yes you're right.
changed

2024-10-15 20:40 UTC, merged