Create dnsdist.subdomain.conf.sample
linuxserver/reverse-proxy-confs pull request #712
Opened 2024-11-02 11:29 UTC by oregonpillow

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ ] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description
Add's dnsdist subdomain nginx conf file to resolve DoH queries at following path: `/dns-query`

## Benefits of this PR and context
Adds powerdns support

## How Has This Been Tested?
- Tested the config with running powerdns dnsdist container.
- `dig @dnsdist.<mydomain> +https google.com` working

## Source / References

2024-11-02 11:29 UTC, oregonpillow commented
Closes #711

2024-11-25 22:38 UTC, Roxedus requested changes

2024-11-26 09:48 UTC, oregonpillow commented
removed redundant directives as you pointed out - thanks.
bumped date
re-tested, still ok  ✅

2024-11-26 16:47 UTC, Roxedus approved these changes

2024-11-26 16:47 UTC, merged