Fix calibre-web.subdomain.conf.sample to work with Kobo
linuxserver/reverse-proxy-confs pull request #714
Opened 2024-11-05 03:37 UTC by Snuupy

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description

Current reverse proxy config doesn't work for kobo

I don't necessarily expect this PR to get merged cus I actually think it's ugly that the `proxy_set_header` stuff is all repeated but it is what it is (current default borks for kobo, this one doesn't)

## Benefits of this PR and context

kobo sync works now instead of fail/error, downloads work too

## How Has This Been Tested?

I have a kobo and this works, original conf doesn't sync NOR download

## Source / References

https://github.com/janeczku/calibre-web/issues/1891#issuecomment-801886803

2024-11-15 22:22 UTC, jgillman requested changes
IDK how to make a commit to your PR so I'll leave it as a comment instead 😅 

If you remove [the changes in the `location /` block](https://github.com/linuxserver/reverse-proxy-confs/pull/714/files#diff-d80794df57fb1daf741fc0356ecf6c5c0c5ae72d2301ec97f47010a4f64aa88aR34-R74) you can simplify them and move them to a new block that will only affect the `/kobo/` endpoint.

At the end of the server block you'd then add:
```nginx
    location /kobo/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app calibre-web;
        set $upstream_port 8083;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header X-Scheme $scheme;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }
```

2024-11-25 22:48 UTC, Roxedus requested changes
Update the date on the top to a date later than what it has now.

2024-11-25 22:48 UTC, Roxedus commented on calibre-web.subdomain.conf.sample
> +        # original proxy.conf config without the incompatible proxy_buffer config
Have you tried overriding the required directives in this conf, rather than straight up circumventing proxy.conf?

2024-11-26 17:28 UTC, aptalca commented
Also, port 80 listen and http-->https redirect is not necessary as it's handled by default in default.conf

2024-12-21 22:55 UTC, drizuid commented
OP didn't respond and i merged a different fix, closing

2024-12-21 22:55 UTC, closed without merging