Discount bandit
linuxserver/reverse-proxy-confs pull request #719
Opened 2024-11-25 22:26 UTC by Findarato

Added support for discount-bandit

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/reverse-proxy-confs/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description

## Benefits of this PR and context

## How Has This Been Tested?
I am using this in my homelab right now.

## Source / References

2024-11-25 22:30 UTC, Findarato commented
I do not think the error is with my pull.

2024-11-26 10:29 UTC, pagdot requested changes
I think you missed a few cosmetic things :)

2024-11-26 10:29 UTC, pagdot commented on discountbandit.subdomain.conf.sample
> +# make sure that your dns has a cname set for <container_name>
Replace `<container_name>` with `discountbandit`

2024-11-26 10:29 UTC, pagdot commented on discountbandit.subdomain.conf.sample
> +        # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
> REMOVE THIS LINE BEFORE SUBMITTING

2024-11-26 10:29 UTC, pagdot commented on discountbandit.subfolder.conf.sample
> +# make sure that <container_name> is set to work with the base url /<container_name>/
Replace `<container_name>` with `discountbandit`

2024-11-26 10:29 UTC, pagdot commented on discountbandit.subfolder.conf.sample
> +    # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
> REMOVE THIS LINE BEFORE SUBMITTING

2024-12-18 17:12 UTC, Findarato commented on discountbandit.subfolder.conf.sample
> +    # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
Thanks I am getting this fixed up

2024-12-18 17:14 UTC, Findarato commented on discountbandit.subdomain.conf.sample
> +        # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
Fixed this

2024-12-19 15:19 UTC, aptalca commented
You might want to do a proper rebase and force push. A brand new PR passes the conf validity check: https://github.com/linuxserver/reverse-proxy-confs/pull/723

Also, please remove the `http2` directives

2024-12-19 15:22 UTC, aptalca commented
hold on, I take it back

You double included the proxy.conf in the subfolder.conf.sample

2024-12-21 22:59 UTC, drizuid requested changes

2024-12-21 22:59 UTC, drizuid commented on discountbandit.subfolder.conf.sample
> +        include /config/nginx/proxy.conf;
dupe will cause errors

2024-12-26 17:25 UTC, drizuid approved these changes

2024-12-26 17:26 UTC, drizuid requested changes
https://github.com/linuxserver/reverse-proxy-confs/pull/719#issuecomment-2554577538

2025-01-01 22:31 UTC, Findarato commented
I am mostly sure I did the rebase correctly.  Crazy how many things change with this repo while I was fixing the mistakes.

2025-01-01 22:34 UTC, Findarato reviewed
Done

2025-01-01 22:34 UTC, Findarato commented
> [#719 (comment)](https://github.com/linuxserver/reverse-proxy-confs/pull/719#issuecomment-2554577538)

I have completed it with https://github.com/linuxserver/reverse-proxy-confs/pull/719/commits/e2b2c6c31407572e610aabc51a6021a17a26cc1f

2025-01-11 05:20 UTC, YouveGotMeowxy commented
is there an image for this app?

2025-01-11 19:19 UTC, drizuid requested changes

2025-01-11 19:19 UTC, drizuid commented on calibre-web.subdomain.conf.sample
why is calibre-web in this pr?

2025-01-11 20:33 UTC, YouveGotMeowxy commented
> is there an image for this app?

Off-topic? I was going to test the reverse proxy out and kinda hard to do it without the app.......

I would think off-topic would be something like if I commented something about the war in ukraine, or my favorite hot dog toppings.

2025-01-12 20:41 UTC, YouveGotMeowxy commented
I'm assuming it's Drizuid marking these as off-topic. Only guy on the team douchey enough to. Definitely a hall monitor back in high school.

2025-04-13 04:01 UTC, closed without merging